-- Run after schema.sql (safe to re-run). Upserts the themes; does not change which one is active.
delete from themes where name in ('dome','kaaba','haram-night');
insert into themes (name, json, active) values
('default', '{"name": "Default", "background": "#0E2A24", "card": "#153A32", "accent": "#E3B95C", "text": "#F4EEDD", "mutedText": "#8FB0A5", "border": "#2A5A4D", "backgroundImage": "", "pattern": "", "glow": "#E3B95C", "fontHeading": "var(--font-heading)", "fontBody": "var(--font-body)", "gradient": "radial-gradient(ellipse at 50% 0%, #1b4a3f 0%, transparent 65%)"}'::jsonb, true),
('modern', '{"name": "Modern", "background": "#0B0D12", "card": "#151922", "accent": "#5CE1C6", "text": "#F2F4F8", "mutedText": "#8B93A5", "border": "#232936", "backgroundImage": "", "pattern": "", "glow": "#5CE1C6", "fontHeading": "var(--font-heading)", "fontBody": "var(--font-body)"}'::jsonb, false),
('geometric', '{"name": "Geometric", "background": "#F3EBDD", "card": "#FFFFFF", "accent": "#B5482F", "text": "#1B2A41", "mutedText": "#6C7A89", "border": "#D9CDB8", "backgroundImage": "", "pattern": "/patterns/geometric.png", "glow": "#B5482F", "fontHeading": "var(--font-heading)", "fontBody": "var(--font-body)"}'::jsonb, false),
('haram', '{"name": "Masjid al-Haram", "background": "#000000", "card": "#000000C7", "accent": "#D4AF37", "text": "#FFFFFF", "mutedText": "#D9CFB4", "border": "#D4AF37AA", "backgroundImage": "/backgrounds/haram-horizontal.jpg", "backgroundImageVertical": "/backgrounds/haram-vertical.jpg", "backgroundPosition": "30% center", "backgroundPositionVertical": "top center", "pattern": "/patterns/haram.png", "glow": "#D4AF37", "fontHeading": "var(--font-heading)", "fontBody": "var(--font-body)"}'::jsonb, false),
('nabawi', '{"name": "Masjid an-Nabawi", "background": "#06392B", "card": "#06392BC2", "accent": "#F2FFF8", "text": "#FFFFFF", "mutedText": "#B5E3CF", "border": "#3DDC9777", "backgroundImage": "/backgrounds/nabawi-horizontal.jpg", "backgroundImageVertical": "/backgrounds/nabawi-vertical.jpg", "backgroundPosition": "center", "backgroundPositionVertical": "center top", "pattern": "/patterns/nabawi.png", "glow": "#3DDC97", "fontHeading": "var(--font-heading)", "fontBody": "var(--font-body)"}'::jsonb, false),
('aqsa', '{"name": "Al-Aqsa", "background": "#0A1B45", "card": "#0A1B45C2", "accent": "#F5C542", "text": "#FFFFFF", "mutedText": "#BCC8E8", "border": "#F5C54277", "backgroundImage": "/backgrounds/aqsa-horizontal.jpg", "backgroundImageVertical": "/backgrounds/aqsa-vertical.jpg", "backgroundPosition": "center", "backgroundPositionVertical": "center top", "pattern": "/patterns/aqsa.png", "glow": "#F5C542", "fontHeading": "var(--font-heading)", "fontBody": "var(--font-body)"}'::jsonb, false)
on conflict (name) do update set json = excluded.json;
-- if the active theme was one of the removed ones, fall back to default
update themes set active = true where name = 'default' and not exists (select 1 from themes where active);
